//Function migration (image list to matrix) for: applycform
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = applycform(varargin)
	select length(varargin)
		case 02 then
			res = il2mat(raw_applycform(mat2il(varargin(01)), varargin(02)))
		else
			error(39)
	end
endfunction