//Function migration (image list to matrix) for: arrowedline
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = arrowedline(varargin)
	select length(varargin)
		case 12 then
			res = il2mat(raw_arrowedline(mat2il(varargin(01)), varargin(02), varargin(03), varargin(04), varargin(05), varargin(06), varargin(07), varargin(08), varargin(09), varargin(10), varargin(11), varargin(12)))
		else
			error(39)
	end
endfunction