//Function migration (image list to matrix) for: boundingRect
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = boundingRect(varargin)
	select length(varargin)
		case 01 then
			res = raw_boundingRect(varargin(01))
		else
			error(39)
	end
endfunction