//Function migration (image list to matrix) for: bwlookup
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = bwlookup(varargin)
	select length(varargin)
		case 02 then
			res = il2mat(raw_bwlookup(mat2il(varargin(01)), varargin(02)))
		else
			error(39)
	end
endfunction