//Function migration (image list to matrix) for: clipline
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = clipline(varargin)
	select length(varargin)
		case 06 then
			res = raw_clipline(varargin(01), varargin(02), varargin(03), varargin(04), varargin(05), varargin(06))
		else
			error(39)
	end
endfunction