//Function migration (image list to matrix) for: convexhull
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = convexhull(varargin)
	select length(varargin)
		case 03 then
			res = raw_convexhull(varargin(01), varargin(02), varargin(03))
		else
			error(39)
	end
endfunction