//Function migration (image list to matrix) for: cornerMinEigenVal
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = cornerMinEigenVal(varargin)
	select length(varargin)
		case 04 then
			res = il2mat(raw_cornerMinEigenVal(mat2il(varargin(01)), varargin(02), varargin(03), varargin(04)))
		else
			error(39)
	end
endfunction