//Function migration (image list to matrix) for: fftshift
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = fftshift(varargin)
	select length(varargin)
		case 01 then
			res = il2mat(raw_fftshift(mat2il(varargin(01))))
		else
			error(39)
	end
endfunction