//Function migration (image list to matrix) for: gaussianblur
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = gaussianblur(varargin)
	select length(varargin)
		case 05 then
			res = il2mat(raw_gaussianblur(mat2il(varargin(01)), varargin(02), varargin(03), varargin(04), varargin(05)))
		else
			error(39)
	end
endfunction