//Function migration (image list to matrix) for: getStructuringElement
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = getStructuringElement(varargin)
	select length(varargin)
		case 05 then
			res = raw_getStructuringElement(varargin(01), varargin(02), varargin(03), varargin(04), varargin(05))
		else
			error(39)
	end
endfunction