//Function migration (image list to matrix) for: grayconnected
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = grayconnected(varargin)
	select length(varargin)
		case 04 then
			res = raw_grayconnected(varargin(01), varargin(02), varargin(03), varargin(04))
		case 03 then
			res = raw_grayconnected(varargin(01), varargin(02), varargin(03))
		else
			error(39)
	end
endfunction