//Function migration (image list to matrix) for: ifftshift
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = ifftshift(varargin)
	select length(varargin)
		case 01 then
			res = il2mat(raw_ifftshift(mat2il(varargin(01))))
		else
			error(39)
	end
endfunction