//Function migration (image list to matrix) for: im2double
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = im2double(varargin)
	select length(varargin)
		case 01 then
			res = il2mat(raw_im2double(mat2il(varargin(01))))
		else
			error(39)
	end
endfunction