//Function migration (image list to matrix) for: imcontrast
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = imcontrast(varargin)
	select length(varargin)
		case 03 then
			res = il2mat(raw_imcontrast(mat2il(varargin(01)), varargin(02), varargin(03)))
		else
			error(39)
	end
endfunction