//Function migration (image list to matrix) for: imgaussfilt3
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = imgaussfilt3(varargin)
	select length(varargin)
		case 02 then
			res = il2mat(raw_imgaussfilt3(mat2il(varargin(01)), varargin(02)))
		case 01 then
			res = il2mat(raw_imgaussfilt3(mat2il(varargin(01))))
		else
			error(39)
	end
endfunction