//Function migration (image list to matrix) for: imresize
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = imresize(varargin)
	select length(varargin)
		case 03 then
			res = il2mat(raw_imresize(mat2il(varargin(01)), varargin(02), varargin(03)))
		else
			error(39)
	end
endfunction