//Function migration (image list to matrix) for: imread
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = imread(varargin)
	select length(varargin)
		case 01 then
			res = il2mat(raw_imread(varargin(01)))
		else
			error(39)
	end
	tempbool = %f
	for i=2:size(res, 3) do
		if cmp(res(:,:,1), res(:,:,i))~=0 then
			tempbool = %t
		end
	end
	if tempbool==%f then
		res= res(:, :, 1)
	end
endfunction