//Function migration (image list to matrix) for: imsharpen
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = imsharpen(varargin)
	select length(varargin)
		case 01 then
			res = il2mat(raw_imsharpen(mat2il(varargin(01))))
		else
			error(39)
	end
endfunction