//Function migration (image list to matrix) for: integralImage
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = integralImage(varargin)
	select length(varargin)
		case 02 then
			res = raw_integralImage(varargin(01), varargin(02))
		case 01 then
			res = raw_integralImage(varargin(01))
		else
			error(39)
	end
endfunction