//Function migration (image list to matrix) for: laplacian
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = laplacian(varargin)
	select length(varargin)
		case 05 then
			res = il2mat(raw_laplacian(mat2il(varargin(01)), varargin(02), varargin(03), varargin(04), varargin(05)))
		else
			error(39)
	end
endfunction