//Function migration (image list to matrix) for: montage
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = montage(varargin)
	select length(varargin)
		case 03 then
			res = il2mat(raw_montage(mat2il(varargin(01)), mat2il(varargin(02)), mat2il(varargin(03))))
		else
			error(39)
	end
endfunction
