//Function migration (image list to matrix) for: newshow
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = newshow(varargin)
	select length(varargin)
		case 01 then
			res = show(mat2il(varargin(01)))
		else
			error(39)
	end
endfunction