//Function migration (image list to matrix) for: pyrUp
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = pyrUp(varargin)
	select length(varargin)
		case 04 then
			res = il2mat(raw_pyrUp(mat2il(varargin(01)), varargin(02), varargin(03), varargin(04)))
		else
			error(39)
	end
endfunction