//Function migration (image list to matrix) for: rectangle
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = rectangle(varargin)
	select length(varargin)
		case 11 then
			res = il2mat(raw_rectangle(mat2il(varargin(01)), varargin(02), varargin(03), varargin(04), varargin(05), varargin(06), varargin(07), varargin(08), varargin(09), varargin(10), varargin(11)))
		else
			error(39)
	end
endfunction