//Function migration (image list to matrix) for: sobel
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = sobel(varargin)
	select length(varargin)
		case 07 then
			res = il2mat(raw_sobel(mat2il(varargin(01)), varargin(02), varargin(03), varargin(04), varargin(05), varargin(06), varargin(07)))
		else
			error(39)
	end
endfunction