//Function migration (image list to matrix) for: whitepoint
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = whitepoint(varargin)
	select length(varargin)
		case 01 then
			res = raw_whitepoint(varargin(01))
		else
			error(39)
	end
endfunction