//Function migration (image list to matrix) for: wiener2
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = wiener2(varargin)
	select length(varargin)
		case 03 then
			res = il2mat(raw_wiener2(mat2il(varargin(01)), varargin(02), varargin(03)))
		else
			error(39)
	end
endfunction