//Function migration (image list to matrix) for: xyz2lab
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = xyz2lab(varargin)
	select length(varargin)
		case 02 then
			res = raw_xyz2lab(varargin(01), varargin(02))
		else
			error(39)
	end
endfunction